# Numpy

### 1D

In [1]:
#importing numpy
import numpy as np

In [2]:
#1D array
arr1=np.array([1,2,3,4,5,6])
print("1D array:",arr1)

1D array: [1 2 3 4 5 6]


In [3]:
#2D array
arr2=np.array([[1,2,3],[2,3,4],[4,5,6],[7,8,9]])
print("2D array:",arr2)

2D array: [[1 2 3]
 [2 3 4]
 [4 5 6]
 [7 8 9]]


In [4]:
#understand attributes
print("Type:",type(arr2))
print("Datatype:",arr1.dtype)
print("Shape:",arr1.shape)
print("Size:",arr1.size)
print("Item size:", arr1.itemsize)
print("No. of Dimensions:", arr1.ndim)
print("No. of bytes:", arr1.nbytes)

Type: <class 'numpy.ndarray'>
Datatype: int64
Shape: (6,)
Size: 6
Item size: 8
No. of Dimensions: 1
No. of bytes: 48


In [5]:
#Creating Special Arrays
#Zeros
arr3=np.zeros((5,2),dtype=int)
print("arr3 with zeroes:",arr3)
arr4=np.ones((3,4),dtype=float)
print("arr4 with ones",arr4)
arr5=np.eye(4,4)
print("arr5 Identity matrix:\n",arr5)
arr6=np.random.rand(3,2)
print("arr6 Random array:\n",arr6)
arr7=np.random.randint(7,size=(2,6))
print("arr7 Random Integer Array:\n",arr7)

arr3 with zeroes: [[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
arr4 with ones [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
arr5 Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
arr6 Random array:
 [[0.25030305 0.56446855]
 [0.50906648 0.87293022]
 [0.53941121 0.10013223]]
arr7 Random Integer Array:
 [[4 1 0 5 6 1]
 [0 1 1 2 3 5]]


In [6]:
#Creating Arrays with "arange"
arr8=np.arange(1,10,2)
print('Array created with arange:',arr8)

Array created with arange: [1 3 5 7 9]


In [7]:
#Creating Arrays with "linspace"
arr9=np.linspace(1,10,50)
print('Array created with linspace requesting 50 elements within 1 to 10:\n',arr9)

Array created with linspace requesting 50 elements within 1 to 10:
 [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [8]:
#Slicing
arr10=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr10)
print("Row2:",arr10[1,:])
print("Column2:",arr10[:,1])
print("Elements 7,8,12,13:\n",arr10[1:3,1:3])
print("All Elements:\n",arr10[:,:])
#Strides
print("Strides:\n",arr10[0::2,1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row2: [ 6  7  8  9 10]
Column2: [ 2  7 12 17]
Elements 7,8,12,13:
 [[ 7  8]
 [12 13]]
All Elements:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


In [9]:
#Masking
arr11=np.array([1,2,3,4,5,6,7,8,9,9])
mask=np.array([0,1,1,0,1,0,1,0,0])
b=arr11[mask]
print(b)

[1 2 2 1 2 1 2 1 1]


In [10]:
arr12=np.array([[1,2,3,4,5],[6,7,8,9,9]])
print(arr12)
print("Sum:\t",np.sum(arr12))
print("Sum:\t", np.sum(arr12,axis=0))
print("Product: \t",np.prod(arr12))
print("Product: \t",np.prod(arr12,axis=0))
print("Minimum:\t",np.min(arr12,axis=0))
print("Maximum:\t",np.max(arr12,axis=0))
print("Mean:\t",np.mean(arr12,axis=0))
print("Variance:\t",np.var(arr12,axis=0))
print("Standard Deviation:\t",np.std(arr12,axis=0))
print("Average:\t",np.average(arr12,axis=0))
print("Weighted Average:\t",np.average(arr12,weights=[1,2,3,4,5],axis=1))

[[1 2 3 4 5]
 [6 7 8 9 9]]
Sum:	 54
Sum:	 [ 7  9 11 13 14]
Product: 	 3265920
Product: 	 [ 6 14 24 36 45]
Minimum:	 [1 2 3 4 5]
Maximum:	 [6 7 8 9 9]
Mean:	 [3.5 4.5 5.5 6.5 7. ]
Variance:	 [6.25 6.25 6.25 6.25 4.  ]
Standard Deviation:	 [2.5 2.5 2.5 2.5 2. ]
Average:	 [3.5 4.5 5.5 6.5 7. ]
Weighted Average:	 [3.66666667 8.33333333]


In [11]:
# Scalar Operations
import numpy as np

arr13 = np.array([1, 2, 3])
arr14 = np.array([4, 5, 6])

# Addition
arr15 = arr13 + arr14
print("Summation:\t", arr15)

# Subtraction
arr16 = arr13 - arr14
print("Difference:\t", arr16)

# Adding scalar to existing array
arr16 += 5
print("Previous output after adding 5:", arr16)

# -------------------------------
# Leftout Scalar Operations
# -------------------------------

# Multiplication
arr17 = arr13 * arr14
print("Multiplication:\t", arr17)

# Division
arr18 = arr14 / arr13
print("Division:\t", arr18)

# Floor Division
arr19 = arr14 // arr13
print("Floor Division:\t", arr19)

# Modulus
arr20 = arr14 % arr13
print("Modulus:\t", arr20)

# Exponentiation (power)
arr21 = arr13 ** 2
print("Exponentiation (arr13 squared):\t", arr21)

# Square root (using NumPy function)
arr22 = np.sqrt(arr14)
print("Square root of arr14:\t", arr22)


Summation:	 [5 7 9]
Difference:	 [-3 -3 -3]
Previous output after adding 5: [2 2 2]
Multiplication:	 [ 4 10 18]
Division:	 [4.  2.5 2. ]
Floor Division:	 [4 2 2]
Modulus:	 [0 1 0]
Exponentiation (arr13 squared):	 [1 4 9]
Square root of arr14:	 [2.         2.23606798 2.44948974]


In [12]:
#Relational operations
result1=arr15==arr16
print(result1)

[False False False]


In [13]:
# Greater than
result2 = arr15 > arr16
print("arr15 > arr16:\t", result2)

# Greater than or equal to
result3 = arr15 >= arr16
print("arr15 >= arr16:\t", result3)

# Less than
result4 = arr15 < arr16
print("arr15 < arr16:\t", result4)

# Less than or equal to
result5 = arr15 <= arr16
print("arr15 <= arr16:\t", result5)

# Not equal to
result6 = arr15 != arr16
print("arr15 != arr16:\t", result6)


arr15 > arr16:	 [ True  True  True]
arr15 >= arr16:	 [ True  True  True]
arr15 < arr16:	 [False False False]
arr15 <= arr16:	 [False False False]
arr15 != arr16:	 [ True  True  True]


In [14]:
#Trigonometric and Logarithmic operations
arr17=np.array([15,30,45,90])
result7=np.sin(arr17)
print("Sin values:\t",result7)
result8=np.log(arr17)
print("Log values:\t",result8)
# Converting degrees to radians for other trig functions
radians_arr17 = np.deg2rad(arr17)

# Cosine values
result9 = np.cos(radians_arr17)
print("Cos values:\t", result9)

# Tangent values
result10 = np.tan(radians_arr17)
print("Tan values:\t", result10)

# Arcsine (inverse sine)
result11 = np.arcsin(np.sin(radians_arr17))
print("Arcsin values (in radians):\t", result11)
print("Arcsin values (in degrees):\t", np.rad2deg(result11))

# Arccos (inverse cosine)
result12 = np.arccos(np.cos(radians_arr17))
print("Arccos values (in radians):\t", result12)
print("Arccos values (in degrees):\t", np.rad2deg(result12))

# Arctan (inverse tangent)
result13 = np.arctan(np.tan(radians_arr17))
print("Arctan values (in radians):\t", result13)
print("Arctan values (in degrees):\t", np.rad2deg(result13))

# Log base 10 values
result14 = np.log10(arr17)
print("Log base 10 values:\t", result14)


Sin values:	 [ 0.65028784 -0.98803162  0.85090352  0.89399666]
Log values:	 [2.7080502  3.40119738 3.80666249 4.49980967]
Cos values:	 [9.65925826e-01 8.66025404e-01 7.07106781e-01 6.12323400e-17]
Tan values:	 [2.67949192e-01 5.77350269e-01 1.00000000e+00 1.63312394e+16]
Arcsin values (in radians):	 [0.26179939 0.52359878 0.78539816 1.57079633]
Arcsin values (in degrees):	 [15. 30. 45. 90.]
Arccos values (in radians):	 [0.26179939 0.52359878 0.78539816 1.57079633]
Arccos values (in degrees):	 [15. 30. 45. 90.]
Arctan values (in radians):	 [0.26179939 0.52359878 0.78539816 1.57079633]
Arctan values (in degrees):	 [15. 30. 45. 90.]
Log base 10 values:	 [1.17609126 1.47712125 1.65321251 1.95424251]


In [15]:
# Sample vectors
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

print("Vector 1:", vec1)
print("Vector 2:", vec2)

# Inner product (same as dot product for 1D arrays)
inner_product = np.inner(vec1, vec2)
print("Inner Product:", inner_product)

# Outer product
outer_product = np.outer(vec1, vec2)
print("Outer Product:\n", outer_product)

# Dot product (matrix multiplication for 1D arrays)
dot_product = np.dot(vec1, vec2)
print("Dot Product:", dot_product)

Vector 1: [1 2 3]
Vector 2: [4 5 6]
Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Dot Product: 32


### 2-D

In [16]:
#Creating a 2D array
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("2D Array:\n", arr2)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#Attributes of 2D arrays
print("Type:", type(arr2))
print("Datatype:", arr2.dtype)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Item size:", arr2.itemsize)
print("No. of Dimensions:", arr2.ndim)
print("No. of bytes:", arr2.nbytes)

Type: <class 'numpy.ndarray'>
Datatype: int64
Shape: (3, 3)
Size: 9
Item size: 8
No. of Dimensions: 2
No. of bytes: 72


In [18]:
#Special 2D Arrays
arr_zeros = np.zeros((3, 4), dtype=int)
print("\nZeros array:\n", arr_zeros)

arr_ones = np.ones((2, 5), dtype=float)
print("\nOnes array:\n", arr_ones)

arr_eye = np.eye(4, 4)
print("\nIdentity matrix:\n", arr_eye)

arr_random = np.random.rand(3, 3)
print("\nRandom array (0 to 1):\n", arr_random)

arr_randint = np.random.randint(10, size=(3, 4))
print("\nRandom Integer array:\n", arr_randint)


Zeros array:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Ones array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Random array (0 to 1):
 [[0.20125167 0.30698252 0.63530854]
 [0.19680654 0.62348429 0.01835012]
 [0.83649463 0.21849825 0.85153113]]

Random Integer array:
 [[1 5 7 4]
 [3 5 7 1]
 [8 1 2 4]]


In [19]:
#Array creation with arange & linspace
arr_arange = np.arange(1, 13).reshape(3, 4)
print("\nArray created with arange:\n", arr_arange)

arr_linspace = np.linspace(1, 10, 12).reshape(3, 4)
print("\nArray created with linspace:\n", arr_linspace)



Array created with arange:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array created with linspace:
 [[ 1.          1.81818182  2.63636364  3.45454545]
 [ 4.27272727  5.09090909  5.90909091  6.72727273]
 [ 7.54545455  8.36363636  9.18181818 10.        ]]


In [20]:
#Slicing in 2D arrays
arr_slice = np.array([[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10],
                      [11, 12, 13, 14, 15],
                      [16, 17, 18, 19, 20]])

print("\nOriginal array:\n", arr_slice)
print("Row 2:", arr_slice[1, :])
print("Column 2:", arr_slice[:, 1])
print("Block [7,8,12,13]:\n", arr_slice[1:3, 1:3])
print("All Elements:\n", arr_slice[:, :])
print("Strides:\n", arr_slice[0::2, 1:3])


Original array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row 2: [ 6  7  8  9 10]
Column 2: [ 2  7 12 17]
Block [7,8,12,13]:
 [[ 7  8]
 [12 13]]
All Elements:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Strides:
 [[ 2  3]
 [12 13]]


In [21]:
#Masking in 2D arrays
arr_mask = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8]])
mask = arr_mask > 4
print("\nBoolean mask:\n", mask)
print("Elements greater than 4:", arr_mask[mask])



Boolean mask:
 [[False False False False]
 [ True  True  True  True]]
Elements greater than 4: [5 6 7 8]


In [22]:
#Mathematical operations on 2D arrays
arr_math = np.array([[1, 2, 3, 4, 5],
                     [6, 7, 8, 9, 9]])

print("\nSum:", np.sum(arr_math))
print("Sum (axis=0):", np.sum(arr_math, axis=0))
print("Product:", np.prod(arr_math))
print("Minimum (axis=0):", np.min(arr_math, axis=0))
print("Maximum (axis=0):", np.max(arr_math, axis=0))
print("Mean (axis=0):", np.mean(arr_math, axis=0))
print("Variance (axis=0):", np.var(arr_math, axis=0))
print("Std Dev (axis=0):", np.std(arr_math, axis=0))
print("Average (axis=0):", np.average(arr_math, axis=0))
print("Weighted Average (axis=1):", np.average(arr_math, weights=[1, 2, 3, 4, 5], axis=1))


Sum: 54
Sum (axis=0): [ 7  9 11 13 14]
Product: 3265920
Minimum (axis=0): [1 2 3 4 5]
Maximum (axis=0): [6 7 8 9 9]
Mean (axis=0): [3.5 4.5 5.5 6.5 7. ]
Variance (axis=0): [6.25 6.25 6.25 6.25 4.  ]
Std Dev (axis=0): [2.5 2.5 2.5 2.5 2. ]
Average (axis=0): [3.5 4.5 5.5 6.5 7. ]
Weighted Average (axis=1): [3.66666667 8.33333333]


In [23]:
#Scalar & Element-wise Operations
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [10, 11, 12]])

print("\nAddition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication:\n", A * B)
print("Division:\n", B / A)
print("Floor Division:\n", B // A)
print("Modulus:\n", B % A)
print("Exponentiation:\n", A ** 2)
print("Square root:\n", np.sqrt(B))


Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]
Floor Division:
 [[7 4 3]
 [2 2 2]]
Modulus:
 [[0 0 0]
 [2 1 0]]
Exponentiation:
 [[ 1  4  9]
 [16 25 36]]
Square root:
 [[2.64575131 2.82842712 3.        ]
 [3.16227766 3.31662479 3.46410162]]


In [24]:
# Relational Operations
print("\nA == B:\n", A == B)
print("A > B:\n", A > B)
print("A < B:\n", A < B)
print("A != B:\n", A != B)


A == B:
 [[False False False]
 [False False False]]
A > B:
 [[False False False]
 [False False False]]
A < B:
 [[ True  True  True]
 [ True  True  True]]
A != B:
 [[ True  True  True]
 [ True  True  True]]


In [25]:
#Trigonometric & Logarithmic
deg_array = np.array([[0, 30, 45],
                      [60, 90, 180]])

radians = np.deg2rad(deg_array)
print("\nSine:\n", np.sin(radians))
print("Cosine:\n", np.cos(radians))
print("Tangent:\n", np.tan(radians))
print("Log base e:\n", np.log(deg_array + 1))
print("Log base 10:\n", np.log10(deg_array + 1))



Sine:
 [[0.00000000e+00 5.00000000e-01 7.07106781e-01]
 [8.66025404e-01 1.00000000e+00 1.22464680e-16]]
Cosine:
 [[ 1.00000000e+00  8.66025404e-01  7.07106781e-01]
 [ 5.00000000e-01  6.12323400e-17 -1.00000000e+00]]
Tangent:
 [[ 0.00000000e+00  5.77350269e-01  1.00000000e+00]
 [ 1.73205081e+00  1.63312394e+16 -1.22464680e-16]]
Log base e:
 [[0.         3.4339872  3.8286414 ]
 [4.11087386 4.51085951 5.19849703]]
Log base 10:
 [[0.         1.49136169 1.66275783]
 [1.78532984 1.95904139 2.25767857]]


In [26]:
#Vector Operations (dot, inner, outer) in 2D
vec1 = np.array([[1, 2, 3]])
vec2 = np.array([[4, 5, 6]])

print("\nVector 1:\n", vec1)
print("Vector 2:\n", vec2)

# Inner product
inner_product = np.inner(vec1.flatten(), vec2.flatten())
print("Inner Product:", inner_product)

# Outer product
outer_product = np.outer(vec1.flatten(), vec2.flatten())
print("Outer Product:\n", outer_product)

# Dot product
dot_product = np.dot(vec1.flatten(), vec2.flatten())
print("Dot Product:", dot_product)


Vector 1:
 [[1 2 3]]
Vector 2:
 [[4 5 6]]
Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Dot Product: 32


# Pandas

In [27]:
#importing pandas
import pandas as pd

In [29]:
#Building Dataframes with pandas from python dictionaries
# dictionary with list object in values
details = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}
# creating a Dataframe object
df = pd.DataFrame(details)
df
print(df)
# DataFrame 2: Car details
car_data = {
    'Brand': ['Toyota', 'Honda', 'Ford', 'BMW'],
    'Year': [2015, 2018, 2017, 2020],
    'Price': [700000, 850000, 600000, 1500000]
}
car_df = pd.DataFrame(car_data)
print("Car DataFrame:")
print(car_df)

# DataFrame 3: Student marks
student_marks = {
    'Name': ['Ravi', 'Priya', 'Amit', 'Sonal'],
    'Maths': [85, 78, 92, 69],
    'Science': [90, 88, 95, 75],
    'English': [80, 85, 78, 82]
}
marks_df = pd.DataFrame(student_marks)
print("\nStudent Marks DataFrame:")
print(marks_df)

        Name  Age University
0      Ankit   23        BHU
1  Aishwarya   21        JNU
2    Shaurya   22         DU
3   Shivangi   21        BHU
Car DataFrame:
    Brand  Year    Price
0  Toyota  2015   700000
1   Honda  2018   850000
2    Ford  2017   600000
3     BMW  2020  1500000

Student Marks DataFrame:
    Name  Maths  Science  English
0   Ravi     85       90       80
1  Priya     78       88       85
2   Amit     92       95       78
3  Sonal     69       75       82


In [30]:
#Create DataFrame from Dictionary with user-defined indexes.
# dictionary with list object in values
details1 = {
    'Name' : ['Ankit', 'Aishwarya', 'Shaurya', 'Shivangi'],
    'Age' : [23, 21, 22, 21],
    'University' : ['BHU', 'JNU', 'DU', 'BHU'],
}

# creating a Dataframe object from dictionary  with custom indexing
df1 = pd.DataFrame(details1, index = ['a', 'b', 'c', 'd'])

df1

Name  Age University
a      Ankit   23        BHU
b  Aishwarya   21        JNU
c    Shaurya   22         DU
d   Shivangi   21        BHU

In [31]:
#Create DataFrame from simple dictionary i.e dictionary with key and simple value like integer or string value.
# dictionary
list1=['S1','S2','S3','S4']
English=[89,90,78,98]
Maths=[67,90,100,100]
Science=[78,89,90,89]
titles=['ID','English','Maths','Science']
values=[list1,English,Maths,Science]
result=list(zip(titles,values))
result

[('ID', ['S1', 'S2', 'S3', 'S4']),
 ('English', [89, 90, 78, 98]),
 ('Maths', [67, 90, 100, 100]),
 ('Science', [78, 89, 90, 89])]

In [32]:
result1=dict(result)
df2=pd.DataFrame(result1)
print(df2)

   ID  English  Maths  Science
0  S1       89     67       78
1  S2       90     90       89
2  S3       78    100       90
3  S4       98    100       89


In [33]:
#Importing Data
df3=pd.read_csv(r'character-deaths.csv')
df3.head()
df3.tail()

Unnamed: 0  1  14.23  1.71  2.43  15.6  127   2.8  3.06  0.28  2.29  \
172         172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   
173         173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   
174         174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35   
175         175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   
176         176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   

     5.64  1.04  3.92  1065  
172   7.7  0.64  1.74   740  
173   7.3  0.70  1.56   750  
174  10.2  0.59  1.56   835  
175   9.3  0.60  1.62   840  
176   9.2  0.61  1.60   560

In [34]:
df3.head(10)

Unnamed: 0  1  14.23  1.71  2.43  15.6  127   2.8  3.06  0.28  2.29  5.64  \
0           0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38   
1           1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68   
2           2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80   
3           3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32   
4           4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75   
5           5  1  14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25   
6           6  1  14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25  5.05   
7           7  1  14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98  5.20   
8           8  1  13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85  7.22   
9           9  1  14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38  5.75   

   1.04  3.92  1065  
0  1.05  3.40  1050  
1  1.03  3.17  1185  
2  0.86  3.45  1480  
3  1.04  2.93   735  
4  1.05  2.85  1450  
5  1.02  3.58  1290  
6  1.06  3.58  1295  
7  1.08  2.85  1045  
8  1.01  3.55  1045  
9  1.25  3.17  1510

In [35]:
df3.tail(10)

Unnamed: 0  1  14.23  1.71  2.43  15.6  127   2.8  3.06  0.28  2.29  \
167         167  3  13.58  2.58  2.69  24.5  105  1.55  0.84  0.39  1.54   
168         168  3  13.40  4.60  2.86  25.0  112  1.98  0.96  0.27  1.11   
169         169  3  12.20  3.03  2.32  19.0   96  1.25  0.49  0.40  0.73   
170         170  3  12.77  2.39  2.28  19.5   86  1.39  0.51  0.48  0.64   
171         171  3  14.16  2.51  2.48  20.0   91  1.68  0.70  0.44  1.24   
172         172  3  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   
173         173  3  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   
174         174  3  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35   
175         175  3  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   
176         176  3  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   

          5.64  1.04  3.92  1065  
167   8.660000  0.74  1.80   750  
168   8.500000  0.67  1.92   630  
169   5.500000  0.66  1.83   510  
170   9.899999  0.57  1.63   470  
171   9.700000  0.62  1.71   660  
172   7.700000  0.64  1.74   740  
173   7.300000  0.70  1.56   750  
174  10.200000  0.59  1.56   835  
175   9.300000  0.60  1.62   840  
176   9.200000  0.61  1.60   560

In [36]:
#Saving processed data frames
df3.to_csv(r'result.csv')

In [37]:
# Try Yourselves:
# Open a file with xls as extension and save it back as a csv file


xls_df = pd.read_excel('character-deaths.xls')

# Display the first few rows to confirm it loaded correctly
print(xls_df.head())

# Save it back as a CSV file
xls_df.to_csv('converted_file.csv', index=False)

print("File has been saved as 'converted_file.csv'")


   Unnamed: 0  1  14.23  1.71  2.43  15.6  127   2.8  3.06  0.28  2.29  5.64  \
0           0  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38   
1           1  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68   
2           2  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80   
3           3  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32   
4           4  1  14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75   

   1.04  3.92  1065  
0  1.05  3.40  1050  
1  1.03  3.17  1185  
2  0.86  3.45  1480  
3  1.04  2.93   735  
4  1.05  2.85  1450  
File has been saved as 'converted_file.csv'


In [38]:
#Creating Index for Entities
df4 = pd.DataFrame({'month': [2, 5, 8, 10],
                   'year': [2017, 2019, 2018, 2019],
                   'sale': [60, 45, 90, 36]})
df4

month  year  sale
0      2  2017    60
1      5  2019    45
2      8  2018    90
3     10  2019    36

In [39]:
#Set the index to become the ‘month’ column:
df4.set_index('month')

year  sale
month            
2      2017    60
5      2019    45
8      2018    90
10     2019    36

In [40]:
#Type and info about dataframe
print("Type:\n",type(df4))
print(df4.head)
print("Shape of dataframe",df4.shape)

Type:
 <class 'pandas.core.frame.DataFrame'>
<bound method NDFrame.head of    month  year  sale
0      2  2017    60
1      5  2019    45
2      8  2018    90
3     10  2019    36>
Shape of dataframe (4, 3)


In [42]:
# Try by yourself:
# Append same data in df4 to df4 itself using concat function
# Print its shape
# Use drop_duplicates to remove duplicates
# Print shape again

# Append df4 to itself
df4 = pd.concat([df4, df4])

# Print shape after appending
print("Shape after appending:", df4.shape)

# Remove duplicates
df4 = df4.drop_duplicates()

# Print shape after removing duplicates
print("Shape after removing duplicates:", df4.shape)


Shape after appending: (8, 3)
Shape after removing duplicates: (4, 3)


In [43]:
print("Columns of dataframe:\t", df2.columns)

Columns of dataframe:	 Index(['ID', 'English', 'Maths', 'Science'], dtype='object')


In [44]:
df2.rename(columns={'Maths':'Mathemtics'},inplace=True)
df2

ID  English  Mathemtics  Science
0  S1       89          67       78
1  S2       90          90       89
2  S3       78         100       90
3  S4       98         100       89

In [45]:
print("Columns of dataframe:\t", df2.columns)

Columns of dataframe:	 Index(['ID', 'English', 'Mathemtics', 'Science'], dtype='object')


In [46]:
print(df2.describe())

         English  Mathemtics    Science
count   4.000000    4.000000   4.000000
mean   88.750000   89.250000  86.500000
std     8.220908   15.564382   5.686241
min    78.000000   67.000000  78.000000
25%    86.250000   84.250000  86.250000
50%    89.500000   95.000000  89.000000
75%    92.000000  100.000000  89.250000
max    98.000000  100.000000  90.000000


In [47]:
print('No. of subjects', df2['Mathemtics'].unique())

No. of subjects [ 67  90 100]


In [48]:
# Accessing using Index
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age':[14, 25, 55, 8, 21]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_
print(df)


       Weight    Name  Age
Row_1      45     Sam   14
Row_2      88  Andrea   25
Row_3      56    Alex   55
Row_4      15   Robin    8
Row_5      71     Kia   21


In [49]:
# return the value
result = df.loc['Row_2', 'Name']

# Print the result
print(result)


Andrea


In [50]:
df.iloc[4]

Weight     71
Name      Kia
Age        21
Name: Row_5, dtype: object

In [51]:
df.iloc[[2,3],[1,2]]
#gets 2nd and 3rd row, 1st and 2nd column data

Name  Age
Row_3   Alex   55
Row_4  Robin    8

In [52]:
df.iloc[:,[1,2]]

Name  Age
Row_1     Sam   14
Row_2  Andrea   25
Row_3    Alex   55
Row_4   Robin    8
Row_5     Kia   21

In [53]:
df.iloc[[1,2],:]

Weight    Name  Age
Row_2      88  Andrea   25
Row_3      56    Alex   55

In [54]:
df.iloc[:2,1:3]
#if slice is a:b, then a is included and b is excluded

Name  Age
Row_1     Sam   14
Row_2  Andrea   25

In [55]:
df2.set_index('English')

ID  Mathemtics  Science
English                         
89       S1          67       78
90       S2          90       89
78       S3         100       90
98       S4         100       89

In [56]:
print(df2.head())

   ID  English  Mathemtics  Science
0  S1       89          67       78
1  S2       90          90       89
2  S3       78         100       90
3  S4       98         100       89


In [57]:
#Use DataFrame.loc attribute to access a particular cell in the given Dataframe using the index and column labels.
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({'Weight':[45, 88, 56, 15, 71],
                   'Name':['Sam', 'Andrea', 'Alex', 'Robin', 'Kia'],
                   'Age':[14, 25, 55, 8, 21]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the DataFrame
print(df)
###Now we will use DataFrame.loc attribute to return the value present in the ‘Name’ column corresponding to the ‘Row_2’ label.
# return the value
result = df.loc['Row_2', 'Name']

# Print the result
print(result)

       Weight    Name  Age
Row_1      45     Sam   14
Row_2      88  Andrea   25
Row_3      56    Alex   55
Row_4      15   Robin    8
Row_5      71     Kia   21
Andrea


In [58]:
##Use DataFrame.loc attribute to return two of the column in the given Dataframe.
# importing pandas as pd
import pandas as pd

# Creating the DataFrame
df = pd.DataFrame({"A":[12, 4, 5, None, 1],
                   "B":[7, 2, 54, 3, None],
                   "C":[20, 16, 11, 3, 8],
                   "D":[14, 3, None, 2, 6]})

# Create the index
index_ = ['Row_1', 'Row_2', 'Row_3', 'Row_4', 'Row_5']

# Set the index
df.index = index_

# Print the DataFrame
print(df)
###Now we will use DataFrame.loc attribute to return the values present in the ‘A’ and ‘D’ column of the Dataframe.
# return the values.
result = df.loc[:, ['A', 'D']]

# Print the result
print(result)

          A     B   C     D
Row_1  12.0   7.0  20  14.0
Row_2   4.0   2.0  16   3.0
Row_3   5.0  54.0  11   NaN
Row_4   NaN   3.0   3   2.0
Row_5   1.0   NaN   8   6.0
          A     D
Row_1  12.0  14.0
Row_2   4.0   3.0
Row_3   5.0   NaN
Row_4   NaN   2.0
Row_5   1.0   6.0


In [59]:
# Try by yourself:
# Creating subsets using relational operators

# Subset with rows where column 'A' > 5
subset_a = df[df['A'] > 5]
print("Rows where A > 5:\n", subset_a, "\n")

# Subset with rows where column 'B' is less than or equal to 10
subset_b = df[df['B'] <= 10]
print("Rows where B <= 10:\n", subset_b, "\n")

# Subset with rows where column 'C' equals 3
subset_c = df[df['C'] == 3]
print("Rows where C == 3:\n", subset_c, "\n")

# Subset with rows where column 'D' is not null
subset_d = df[df['D'].notnull()]
print("Rows where D is not null:\n", subset_d)


Rows where A > 5:
           A    B   C     D
Row_1  12.0  7.0  20  14.0 

Rows where B <= 10:
           A    B   C     D
Row_1  12.0  7.0  20  14.0
Row_2   4.0  2.0  16   3.0
Row_4   NaN  3.0   3   2.0 

Rows where C == 3:
         A    B  C    D
Row_4 NaN  3.0  3  2.0 

Rows where D is not null:
           A    B   C     D
Row_1  12.0  7.0  20  14.0
Row_2   4.0  2.0  16   3.0
Row_4   NaN  3.0   3   2.0
Row_5   1.0  NaN   8   6.0


In [60]:
##Groupby
import pandas as pd

ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
   'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
   'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
   'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
   'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)

print(df)

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690


In [61]:
#To group by teams
print(df.groupby('Team'))

In [62]:
# To view group
print(df.groupby('Team').groups)

{'Devils': [2, 3], 'Kings': [4, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10], 'kings': [5]}


In [63]:
#Groupby multiple columns
print(df.groupby(['Team','Year']).groups)

{('Devils', 2014): [2], ('Devils', 2015): [3], ('Kings', 2014): [4], ('Kings', 2016): [6], ('Kings', 2017): [7], ('Riders', 2014): [0], ('Riders', 2015): [1], ('Riders', 2016): [8], ('Riders', 2017): [11], ('Royals', 2014): [9], ('Royals', 2015): [10], ('kings', 2015): [5]}


In [64]:
#Iterating through Groups
grouped = df.groupby('Year')

for name,group in grouped:
   print(name)
   print(group)

2014
     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
2015
      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    kings     4  2015     812
10  Royals     1  2015     804
2016
     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694
2017
      Team  Rank  Year  Points
7    Kings     1  2017     788
11  Riders     2  2017     690


In [65]:
#Select a Group
grouped = df.groupby('Year')
print(grouped.get_group(2014))

     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701


In [66]:
###Aggregations
import numpy as np
grouped = df.groupby('Year')
print(grouped['Points'].agg(np.mean))
print(grouped['Points'].agg(np.sum))

Year
2014    795.25
2015    769.50
2016    725.00
2017    739.00
Name: Points, dtype: float64
Year
2014    3181
2015    3078
2016    1450
2017    1478
Name: Points, dtype: int64


/tmp/ipython-input-1485996890.py:4: FutureWarning: The provided callable <function mean at 0x7b3087d1e700> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(grouped['Points'].agg(np.mean))
/tmp/ipython-input-1485996890.py:5: FutureWarning: The provided callable <function sum at 0x7b3087d1d620> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(grouped['Points'].agg(np.sum))


In [67]:
#Applying Multiple Aggregation Functions at Once
grouped = df.groupby('Team')
print(grouped['Points'].agg([np.sum, np.mean, np.std]))

         sum        mean         std
Team                                
Devils  1536  768.000000  134.350288
Kings   2285  761.666667   24.006943
Riders  3049  762.250000   88.567771
Royals  1505  752.500000   72.831998
kings    812  812.000000         NaN


/tmp/ipython-input-1578159318.py:3: FutureWarning: The provided callable <function sum at 0x7b3087d1d620> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  print(grouped['Points'].agg([np.sum, np.mean, np.std]))
/tmp/ipython-input-1578159318.py:3: FutureWarning: The provided callable <function mean at 0x7b3087d1e700> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  print(grouped['Points'].agg([np.sum, np.mean, np.std]))
/tmp/ipython-input-1578159318.py:3: FutureWarning: The provided callable <function std at 0x7b3087d1e840> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  print(grouped['Points'].agg([np.sum, np.mean, np.st